name: Multiplatform Build

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build-android:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        java-package: 'jdk'
        check-latest: false
        server-id: github
        server-username: ${{ secrets.GITHUB_ACTOR }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true

    - name: Create local.properties
      run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> local.properties
          echo "BASE_URL_BACKEND_ANDROID_EMU=${{ secrets.BASE_URL_BACKEND_ANDROID_EMU }}" >> local.properties
          echo "BASE_URL_BACKEND_IOS_EMU=${{ secrets.BASE_URL_BACKEND_IOS_EMU }}" >> local.properties

    - name: Refresh Gradle dependencies if requested
      if: contains(github.event.head_commit.message, '[refresh-dependencies]')
      run: ./gradlew --refresh-dependencies

    - name: Build Android
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: composeApp-debug.apk
        path: composeApp/build/outputs/apk/debug/composeApp-debug.apk

  build-ios:
    runs-on: macos-latest
    strategy:
      matrix:
        architecture: [arm64, simulatorArm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        java-package: 'jdk'
        check-latest: false
        server-id: github
        server-username: ${{ secrets.GITHUB_ACTOR }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true

    - name: Create local.properties
      run: |
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> local.properties
        echo "BASE_URL_BACKEND_ANDROID_EMU=${{ secrets.BASE_URL_BACKEND_ANDROID_EMU }}" >> local.properties
        echo "BASE_URL_BACKEND_IOS_EMU=${{ secrets.BASE_URL_BACKEND_IOS_EMU }}" >> local.properties

    - name: Refresh Gradle dependencies if requested
      if: contains(github.event.head_commit.message, '[refresh-dependencies]')
      run: ./gradlew --refresh-dependencies

    - name: Build iOS ${{ matrix.architecture }} framework
      run: ./gradlew :composeApp:linkDebugFrameworkIos${{ matrix.architecture }}
